# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 01:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='PicTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.FileField(upload_to='blog/')),
            ],
        ),
        migrations.CreateModel(
            name='SortTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.PicTable'),
        ),
        migrations.AddField(
            model_name='blog',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.SortTable', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
    ]
